### ISSUE TITLE
Have a look at Open-Source-Programs

### ISSUE THREAD

**Issue by sks444** [Catalyst-SMVD/Open-Source-Events#6]
https://github.com/tapaswenipathak/Open-Source-Programs

**Comment by anubhavsingh16** [comment]
Thanks @sks444 sir, Sir is it ok if I use this list in project and mention all events according to month?

**Comment by sks444** [comment]
Yeah, if you think it will be helpful to others, you could do it.

P.S. There is no need to add `sir`. ;-)

**Comment by anubhavsingh16** [comment]
Ok 😁
